<?php
/**
 * Create the local editor login for standalone (non-WordPress) runs.
 *
 *     php make-admin-password.php "your-password"
 *     php make-admin-password.php "your-password" someuser     (default user: admin)
 *
 * Writes admin-credentials.php next to this file, containing a password_hash()
 * and never the password itself. That file is gitignored: the whole reason the
 * old hard-coded list in save_content.php was a problem is that it was committed,
 * so anyone reading the repository could log in to the live site.
 *
 * Once the site runs on real WordPress this file is not used at all - login goes
 * through wp_authenticate() and the WordPress user table, and admin-credentials.php
 * can be deleted.
 *
 * CLI only. Serving it over HTTP would let a visitor reset the editor password.
 */

if (PHP_SAPI !== 'cli') {
    http_response_code(403);
    exit("This script can only be run from the command line.\n");
}

$password = isset($argv[1]) ? $argv[1] : '';
$user     = isset($argv[2]) ? $argv[2] : 'admin';

if ($password === '') {
    fwrite(STDERR, "Usage: php make-admin-password.php \"your-password\" [username]\n");
    exit(1);
}
if (strlen($password) < 8) {
    fwrite(STDERR, "Password must be at least 8 characters.\n");
    exit(1);
}

$hash = password_hash($password, PASSWORD_DEFAULT);
$file = __DIR__ . '/admin-credentials.php';

$contents = "<?php\n"
    . "/* Generated by make-admin-password.php. Gitignored - do not commit.\n"
    . "   Used only when this theme runs without WordPress. */\n"
    . "return array(\n"
    . "    'user' => " . var_export($user, true) . ",\n"
    . "    'hash' => " . var_export($hash, true) . ",\n"
    . ");\n";

if (file_put_contents($file, $contents) === false) {
    fwrite(STDERR, "Could not write $file\n");
    exit(1);
}
@chmod($file, 0600);

echo "Wrote " . $file . "\n";
echo "  username: " . $user . "\n";
echo "  password: (the one you just typed - it is not stored, only its hash)\n";
echo "\nLog in at /?login=true\n";
